version: "1.1"
stages:
  - stage:
      - git-checkout:
          alias: git-checkout
          description: 代码仓库克隆
  - stage:
      - custom-script:
          alias: docker-push
          description: 运行自定义命令
          image: registry.erda.cloud/retag/docker
          commands:
            - cd ${git-checkout}
            - echo "http://mirrors.aliyun.com/alpine/v3.6/main/" > /etc/apk/repositories && echo "http://mirrors.aliyun.com/alpine/v3.6/community/" >> /etc/apk/repositories
            - time=`date +%s%6N`
            - image='registry.erda.cloud/erda/erda-custom-app:'((dice.version))'-'((date.YYYYMMDD))'-'"$time" # your app name
            - docker build --build-arg NODE_OPTIONS=--max_old_space_size=3996 --cpu-quota 100000 --memory 4294967296 -t $image -f Dockerfile .
            - docker login registry.erda.cloud/erda -u=((dockerUsername)) -p=((dockerPassword))
            - docker push $image
            - echo "image="$image"" >> $METAFILE
          resources:
            cpu: 1
            mem: 4000
  - stage:
      - release:
          alias: release
          description: 用于打包完成时，向dicehub 提交完整可部署的dice.yml。用户若没在pipeline.yml里定义该action，CI会自动在pipeline.yml里插入该action
          params:
            dice_yml: ${git-checkout}/erda.yml
            image:
              custom-app-ui: ${docker-push:OUTPUT:image} # your app name
